import { Member, Activity } from "./types";
import { calculateActivityState } from "./state-engine";
import { SEED_REFERENCE_DATE } from "./date-utils";

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "m1",
    name: "Aarav Mehta",
    role: "Finance Transformation Lead",
    company: "Meridian Systems",
    primarySpace: "Tools & Systems",
    owner: "Community Team",
    joinedDate: "2026-01-10",
    notes: "Key contributor on ERP implementations and automation.",
    nextAction: "Invite contribution to Tools & Systems",
    commercialSignal: "Evaluating new ERP vendor for Q4 deployment — requested vendor recommendations from peers.",
    createdAt: "2026-01-10T08:00:00Z",
  },
  {
    id: "m2",
    name: "Priya Nair",
    role: "FP&A Manager",
    company: "Northstar Foods",
    primarySpace: "Ask Finance Peers",
    owner: "Community Team",
    joinedDate: "2026-02-03",
    notes: "Active in quarterly close workflows and budgeting.",
    nextAction: "Explore guest article on FP&A close templates",
    commercialSignal: null,
    createdAt: "2026-02-03T08:00:00Z",
  },
  {
    id: "m3",
    name: "Rohan Kapoor",
    role: "Controller",
    company: "Vertex Manufacturing",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2025-11-12",
    notes: "Focuses on month-end close efficiency.",
    nextAction: "Check in on month-end close discussion",
    commercialSignal: null,
    createdAt: "2025-11-12T08:00:00Z",
  },
  {
    id: "m4",
    name: "Ananya Rao",
    role: "Finance Systems Manager",
    company: "BluePeak Retail",
    primarySpace: "Tools & Systems",
    owner: "Community Team",
    joinedDate: "2025-12-01",
    notes: "Interested in reconciliation tool comparisons.",
    nextAction: "Share upcoming ERP discussion thread",
    commercialSignal: null,
    createdAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "m5",
    name: "Karan Shah",
    role: "Treasury Manager",
    company: "Atlas Mobility",
    primarySpace: "Tools & Systems",
    owner: "Community Team",
    joinedDate: "2026-03-05",
    notes: "Treasury dashboard expert.",
    nextAction: "Invite to facilitate treasury tech roundtable",
    commercialSignal: "Company raising Series B — expanding treasury management needs.",
    createdAt: "2026-03-05T08:00:00Z",
  },
  {
    id: "m6",
    name: "Meera Iyer",
    role: "Senior Finance Analyst",
    company: "Cedar Analytics",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2026-08-15",
    notes: "Newly joined member needing onboarding support.",
    nextAction: "Send welcome message & invite to Say Hello",
    commercialSignal: null,
    createdAt: "2026-08-15T08:00:00Z",
  },
  {
    id: "m7",
    name: "Vikram Menon",
    role: "CFO",
    company: "Lumina HealthTech",
    primarySpace: "Ask Finance Peers",
    owner: "Community Team",
    joinedDate: "2026-01-22",
    notes: "Executive level community participant.",
    nextAction: "Tag in peer executive discussion",
    commercialSignal: "Planning team expansion — mentioned hiring 3 FP&A leads.",
    createdAt: "2026-01-22T08:00:00Z",
  },
  {
    id: "m8",
    name: "Sneha Patel",
    role: "Accounts Payable Lead",
    company: "Harbor Commerce",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2025-09-04",
    notes: "AP automation background.",
    nextAction: "Surface recent AP automation thread",
    commercialSignal: null,
    createdAt: "2025-09-04T08:00:00Z",
  },
  {
    id: "m9",
    name: "Aditya Verma",
    role: "FP&A Analyst",
    company: "Nova Energy",
    primarySpace: "Ask Finance Peers",
    owner: "Community Team",
    joinedDate: "2026-04-18",
    notes: "Shares rolling forecast templates.",
    nextAction: "Highlight rolling forecast post in weekly digest",
    commercialSignal: null,
    createdAt: "2026-04-18T08:00:00Z",
  },
  {
    id: "m10",
    name: "Divya Krishnan",
    role: "Finance Operations Manager",
    company: "Orbit Logistics",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2025-10-09",
    notes: "Logistics close-cycle expert.",
    nextAction: "Invite to share logistics close-cycle tip in digest",
    commercialSignal: null,
    createdAt: "2025-10-09T08:00:00Z",
  },
  {
    id: "m11",
    name: "Nikhil Rao",
    role: "AR Manager",
    company: "Crest Services",
    primarySpace: "Say Hello",
    owner: "Community Team",
    joinedDate: "2026-08-12",
    notes: "Recently introduced himself.",
    nextAction: "Encourage first question in Ask Finance Peers",
    commercialSignal: null,
    createdAt: "2026-08-12T08:00:00Z",
  },
  {
    id: "m12",
    name: "Pooja Shah",
    role: "Finance Analyst",
    company: "Greenfield Foods",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2026-02-14",
    notes: "Inactive for over 60 days.",
    nextAction: "Evaluate light check-in email",
    commercialSignal: null,
    createdAt: "2026-02-14T08:00:00Z",
  },
  {
    id: "m13",
    name: "Rahul Joshi",
    role: "Finance Transformation Manager",
    company: "Axis Digital",
    primarySpace: "Tools & Systems",
    owner: "Community Team",
    joinedDate: "2026-08-17",
    notes: "New member, zero activities.",
    nextAction: "Send onboarding guide & ask about ERP goals",
    commercialSignal: null,
    createdAt: "2026-08-17T08:00:00Z",
  },
  {
    id: "m14",
    name: "Tanya Menon",
    role: "Senior Accountant",
    company: "Silverline Media",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2025-08-22",
    notes: "Stale activity history.",
    nextAction: "Share relevant accounting standards thread",
    commercialSignal: null,
    createdAt: "2025-08-22T08:00:00Z",
  },
  {
    id: "m15",
    name: "Devika Nair",
    role: "Treasury Analyst",
    company: "Eastbridge Capital",
    primarySpace: "Ask Finance Peers",
    owner: "Community Team",
    joinedDate: "2025-11-30",
    notes: "Occasional cash-flow contributor.",
    nextAction: "Share cash flow management template",
    commercialSignal: null,
    createdAt: "2025-11-30T08:00:00Z",
  },
  {
    id: "m16",
    name: "Arjun Pillai",
    role: "Finance Manager",
    company: "Westlake Technologies",
    primarySpace: "Say Hello",
    owner: "Community Team",
    joinedDate: "2026-08-09",
    notes: "Posted introduction 10 days ago.",
    nextAction: "Suggest sharing a finance workflow question",
    commercialSignal: null,
    createdAt: "2026-08-09T08:00:00Z",
  },
  {
    id: "m17",
    name: "Neha Kapoor",
    role: "FP&A Lead",
    company: "Horizon Consumer",
    primarySpace: "Career & Compensation",
    owner: "Community Team",
    joinedDate: "2025-07-03",
    notes: "Comp-benchmarking contributor.",
    nextAction: "Share compensation benchmarking update",
    commercialSignal: null,
    createdAt: "2025-07-03T08:00:00Z",
  },
  {
    id: "m18",
    name: "Sameer Rao",
    role: "Accounting Manager",
    company: "Riverstone Infrastructure",
    primarySpace: "Finance Workflows",
    owner: "Community Team",
    joinedDate: "2026-01-05",
    notes: "Silent for 90+ days.",
    nextAction: "Review for quarterly re-engagement campaign",
    commercialSignal: null,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "m19",
    name: "Isha Menon",
    role: "Finance Systems Analyst",
    company: "Clearpath Software",
    primarySpace: "Tools & Systems",
    owner: "Community Team",
    joinedDate: "2025-08-30",
    notes: "Silent for 130+ days.",
    nextAction: "Send annual community check-in survey",
    commercialSignal: null,
    createdAt: "2025-08-30T08:00:00Z",
  },
  {
    id: "m20",
    name: "Ritesh Kumar",
    role: "Controller",
    company: "Summit Services",
    primarySpace: "Tools & Systems",
    owner: "Community Team",
    joinedDate: "2025-10-20",
    notes: "Internal controls specialist.",
    nextAction: "Tag in internal controls discussion",
    commercialSignal: null,
    createdAt: "2025-10-20T08:00:00Z",
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  // 1. Aarav Mehta (Highly Active)
  {
    id: "act-1-1",
    memberId: "m1",
    date: "2026-08-18",
    space: "Tools & Systems",
    type: "Comment",
    description: "Shared ERP migration approach",
    engagement: "High",
    recordedBy: "Community Team",
    recordedAt: "2026-08-18T15:30:00Z",
    createdAt: "2026-08-18T15:30:00Z",
  },
  {
    id: "act-1-2",
    memberId: "m1",
    date: "2026-08-16",
    space: "Finance Workflows",
    type: "Post",
    description: "Shared quarterly forecasting template",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-16T11:00:00Z",
    createdAt: "2026-08-16T11:00:00Z",
  },
  {
    id: "act-1-3",
    memberId: "m1",
    date: "2026-08-14",
    space: "Tools & Systems",
    type: "Comment",
    description: "Answered question on account reconciliation",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-14T09:20:00Z",
    createdAt: "2026-08-14T09:20:00Z",
  },
  {
    id: "act-1-4",
    memberId: "m1",
    date: "2026-08-10",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Shared process for monthly close",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-10T14:15:00Z",
    createdAt: "2026-08-10T14:15:00Z",
  },

  // 2. Priya Nair (Highly Active)
  {
    id: "act-2-1",
    memberId: "m2",
    date: "2026-08-19",
    space: "Ask Finance Peers",
    type: "Post",
    description: "Shared quarterly close checklist",
    engagement: "High",
    recordedBy: "Community Team",
    recordedAt: "2026-08-19T09:00:00Z",
    createdAt: "2026-08-19T09:00:00Z",
  },
  {
    id: "act-2-2",
    memberId: "m2",
    date: "2026-08-15",
    space: "Finance Workflows",
    type: "Comment",
    description: "Answered a workflow question",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-15T16:45:00Z",
    createdAt: "2026-08-15T16:45:00Z",
  },
  {
    id: "act-2-3",
    memberId: "m2",
    date: "2026-08-09",
    space: "Career & Compensation",
    type: "Comment",
    description: "Weighed in on comp benchmarking thread",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-08-09T10:30:00Z",
    createdAt: "2026-08-09T10:30:00Z",
  },

  // 3. Rohan Kapoor (Active)
  {
    id: "act-3-1",
    memberId: "m3",
    date: "2026-08-02",
    space: "Finance Workflows",
    type: "Comment",
    description: "Discussed month-end close process",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-02T13:00:00Z",
    createdAt: "2026-08-02T13:00:00Z",
  },
  {
    id: "act-3-2",
    memberId: "m3",
    date: "2026-07-20",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered an onboarding question",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-07-20T11:20:00Z",
    createdAt: "2026-07-20T11:20:00Z",
  },

  // 4. Ananya Rao (Active)
  {
    id: "act-4-1",
    memberId: "m4",
    date: "2026-07-28",
    space: "Tools & Systems",
    type: "Post",
    description: "Shared a reconciliation checklist",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-07-28T14:00:00Z",
    createdAt: "2026-07-28T14:00:00Z",
  },
  {
    id: "act-4-2",
    memberId: "m4",
    date: "2026-07-10",
    space: "Finance Workflows",
    type: "Comment",
    description: "Weighed in on close-cycle timing",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-10T10:00:00Z",
    createdAt: "2026-07-10T10:00:00Z",
  },

  // 5. Karan Shah (Highly Active)
  {
    id: "act-5-1",
    memberId: "m5",
    date: "2026-08-17",
    space: "Tools & Systems",
    type: "Post",
    description: "Shared treasury dashboard template",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-17T16:00:00Z",
    createdAt: "2026-08-17T16:00:00Z",
  },
  {
    id: "act-5-2",
    memberId: "m5",
    date: "2026-08-13",
    space: "Finance Workflows",
    type: "Comment",
    description: "Discussed cash flow forecasting",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-13T12:00:00Z",
    createdAt: "2026-08-13T12:00:00Z",
  },
  {
    id: "act-5-3",
    memberId: "m5",
    date: "2026-08-07",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered a treasury policy question",
    engagement: "High",
    recordedBy: "Community Team",
    recordedAt: "2026-08-07T15:00:00Z",
    createdAt: "2026-08-07T15:00:00Z",
  },

  // 6. Meera Iyer (Newly Joined - 1 activity)
  {
    id: "act-6-1",
    memberId: "m6",
    date: "2026-08-16",
    space: "Say Hello",
    type: "Introduction",
    description: "Introduced herself to the community as Senior Finance Analyst at Cedar Analytics",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-08-16T10:00:00Z",
    createdAt: "2026-08-16T10:00:00Z",
  },

  // 7. Vikram Menon (Active)
  {
    id: "act-7-1",
    memberId: "m7",
    date: "2026-08-03",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered a process question",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-03T10:00:00Z",
    createdAt: "2026-08-03T10:00:00Z",
  },
  {
    id: "act-7-2",
    memberId: "m7",
    date: "2026-07-22",
    space: "Finance Workflows",
    type: "Comment",
    description: "Weighed in on a workflow discussion",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-22T14:30:00Z",
    createdAt: "2026-07-22T14:30:00Z",
  },

  // 8. Sneha Patel (At Risk)
  {
    id: "act-8-1",
    memberId: "m8",
    date: "2026-07-15",
    space: "Career & Compensation",
    type: "Comment",
    description: "Weighed in on compensation structures",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-15T11:00:00Z",
    createdAt: "2026-07-15T11:00:00Z",
  },
  {
    id: "act-8-2",
    memberId: "m8",
    date: "2026-07-03",
    space: "Finance Workflows",
    type: "Comment",
    description: "Discussed AP process",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-03T09:30:00Z",
    createdAt: "2026-07-03T09:30:00Z",
  },
  {
    id: "act-8-3",
    memberId: "m8",
    date: "2026-06-18",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered a vendor management question",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-06-18T16:00:00Z",
    createdAt: "2026-06-18T16:00:00Z",
  },

  // 9. Aditya Verma (Highly Active)
  {
    id: "act-9-1",
    memberId: "m9",
    date: "2026-08-18",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Shared a variance analysis approach",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-18T14:00:00Z",
    createdAt: "2026-08-18T14:00:00Z",
  },
  {
    id: "act-9-2",
    memberId: "m9",
    date: "2026-08-15",
    space: "Finance Workflows",
    type: "Post",
    description: "Shared a rolling forecast template",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-15T10:00:00Z",
    createdAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "act-9-3",
    memberId: "m9",
    date: "2026-08-12",
    space: "Tools & Systems",
    type: "Comment",
    description: "Answered a systems integration question",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-12T11:30:00Z",
    createdAt: "2026-08-12T11:30:00Z",
  },

  // 10. Divya Krishnan (Active)
  {
    id: "act-10-1",
    memberId: "m10",
    date: "2026-07-30",
    space: "Finance Workflows",
    type: "Post",
    description: "Shared a logistics close-cycle tip",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-07-30T15:00:00Z",
    createdAt: "2026-07-30T15:00:00Z",
  },
  {
    id: "act-10-2",
    memberId: "m10",
    date: "2026-07-12",
    space: "Tools & Systems",
    type: "Comment",
    description: "Weighed in on systems discussion",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-12T13:00:00Z",
    createdAt: "2026-07-12T13:00:00Z",
  },

  // 11. Nikhil Rao (Newly Joined - 1 activity)
  {
    id: "act-11-1",
    memberId: "m11",
    date: "2026-08-13",
    space: "Say Hello",
    type: "Introduction",
    description: "Introduced themselves to the community",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-08-13T09:00:00Z",
    createdAt: "2026-08-13T09:00:00Z",
  },

  // 12. Pooja Shah (Dormant)
  {
    id: "act-12-1",
    memberId: "m12",
    date: "2026-06-08",
    space: "Finance Workflows",
    type: "Comment",
    description: "Weighed in on tools discussion",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-06-08T10:00:00Z",
    createdAt: "2026-06-08T10:00:00Z",
  },
  {
    id: "act-12-2",
    memberId: "m12",
    date: "2026-05-28",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered a process question",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-05-28T14:00:00Z",
    createdAt: "2026-05-28T14:00:00Z",
  },
  {
    id: "act-12-3",
    memberId: "m12",
    date: "2026-05-15",
    space: "Say Hello",
    type: "Introduction",
    description: "Posted first introduction",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-05-15T09:00:00Z",
    createdAt: "2026-05-15T09:00:00Z",
  },

  // 13. Rahul Joshi (Newly Joined - 1 activity)
  {
    id: "act-13-1",
    memberId: "m13",
    date: "2026-08-18",
    space: "Tools & Systems",
    type: "Question",
    description: "Asked a peer question about ERP implementation timelines",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-08-18T11:00:00Z",
    createdAt: "2026-08-18T11:00:00Z",
  },

  // 14. Tanya Menon (At Risk)
  {
    id: "act-14-1",
    memberId: "m14",
    date: "2026-06-30",
    space: "Finance Workflows",
    type: "Comment",
    description: "Weighed in on a workflow thread",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-06-30T11:00:00Z",
    createdAt: "2026-06-30T11:00:00Z",
  },
  {
    id: "act-14-2",
    memberId: "m14",
    date: "2026-06-10",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered a peer question",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-06-10T15:00:00Z",
    createdAt: "2026-06-10T15:00:00Z",
  },

  // 15. Devika Nair (Active)
  {
    id: "act-15-1",
    memberId: "m15",
    date: "2026-08-01",
    space: "Ask Finance Peers",
    type: "Comment",
    description: "Weighed in on a treasury thread",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-01T10:00:00Z",
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "act-15-2",
    memberId: "m15",
    date: "2026-07-15",
    space: "Finance Workflows",
    type: "Answer",
    description: "Answered a cash-flow question",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-15T14:00:00Z",
    createdAt: "2026-07-15T14:00:00Z",
  },

  // 16. Arjun Pillai (Newly Joined - 1 activity)
  {
    id: "act-16-1",
    memberId: "m16",
    date: "2026-08-10",
    space: "Say Hello",
    type: "Introduction",
    description: "Introduced themselves to the community",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-08-10T10:00:00Z",
    createdAt: "2026-08-10T10:00:00Z",
  },

  // 17. Neha Kapoor (At Risk)
  {
    id: "act-17-1",
    memberId: "m17",
    date: "2026-07-05",
    space: "Career & Compensation",
    type: "Post",
    description: "Shared a comp-benchmarking article",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-05T12:00:00Z",
    createdAt: "2026-07-05T12:00:00Z",
  },
  {
    id: "act-17-2",
    memberId: "m17",
    date: "2026-06-22",
    space: "Tools & Systems",
    type: "Comment",
    description: "Weighed in on systems discussion",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-06-22T15:00:00Z",
    createdAt: "2026-06-22T15:00:00Z",
  },

  // 18. Sameer Rao (Dormant)
  {
    id: "act-18-1",
    memberId: "m18",
    date: "2026-05-20",
    space: "Finance Workflows",
    type: "Comment",
    description: "Weighed in on close-cycle timing",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-05-20T11:00:00Z",
    createdAt: "2026-05-20T11:00:00Z",
  },
  {
    id: "act-18-2",
    memberId: "m18",
    date: "2026-04-30",
    space: "Ask Finance Peers",
    type: "Answer",
    description: "Answered a reconciliation question",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-04-30T14:00:00Z",
    createdAt: "2026-04-30T14:00:00Z",
  },

  // 19. Isha Menon (Dormant)
  {
    id: "act-19-1",
    memberId: "m19",
    date: "2026-04-10",
    space: "Tools & Systems",
    type: "Comment",
    description: "Weighed in on a systems thread",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-04-10T09:00:00Z",
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "act-19-2",
    memberId: "m19",
    date: "2026-03-22",
    space: "Say Hello",
    type: "Introduction",
    description: "Posted first introduction",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-03-22T10:00:00Z",
    createdAt: "2026-03-22T10:00:00Z",
  },

  // 20. Ritesh Kumar (Active)
  {
    id: "act-20-1",
    memberId: "m20",
    date: "2026-07-25",
    space: "Tools & Systems",
    type: "Post",
    description: "Shared a controls checklist",
    engagement: "Medium",
    recordedBy: "Community Team",
    recordedAt: "2026-07-25T16:00:00Z",
    createdAt: "2026-07-25T16:00:00Z",
  },
  {
    id: "act-20-2",
    memberId: "m20",
    date: "2026-07-05",
    space: "Ask Finance Peers",
    type: "Comment",
    description: "Weighed in on a peer question",
    engagement: "Low",
    recordedBy: "Community Team",
    recordedAt: "2026-07-05T10:00:00Z",
    createdAt: "2026-07-05T10:00:00Z",
  },
];

export function validateSeedData(
  members: Member[] = INITIAL_MEMBERS,
  activities: Activity[] = INITIAL_ACTIVITIES,
  referenceDate: string = SEED_REFERENCE_DATE
): {
  isValid: boolean;
  distribution: Record<string, number>;
  expected: Record<string, number>;
  errors: string[];
} {
  const expected = {
    NewlyJoined: 4,
    Active: 6,
    HighlyActive: 4,
    AtRisk: 3,
    Dormant: 3,
  };

  const distribution: Record<string, number> = {
    NewlyJoined: 0,
    Active: 0,
    HighlyActive: 0,
    AtRisk: 0,
    Dormant: 0,
  };

  const errors: string[] = [];

  if (members.length !== 20) {
    errors.push(`Expected 20 members, found ${members.length}`);
  }

  members.forEach((member) => {
    if (!member.name || !member.role || !member.company || !member.primarySpace) {
      errors.push(`Member ${member.id || "unknown"} is missing required fields`);
    }

    const memberActivities = activities.filter((a) => a.memberId === member.id);
    const { state } = calculateActivityState(member, memberActivities, referenceDate);
    distribution[state] = (distribution[state] || 0) + 1;
  });

  activities.forEach((act) => {
    if (!act.memberId || !act.date || !act.type || !act.space) {
      errors.push(`Activity ${act.id || "unknown"} is missing required fields`);
    }
  });

  let isValid = true;
  for (const key of Object.keys(expected) as Array<keyof typeof expected>) {
    if (distribution[key] !== expected[key]) {
      isValid = false;
      errors.push(
        `Distribution mismatch for ${key}: expected ${expected[key]}, got ${distribution[key]}`
      );
    }
  }

  return {
    isValid: isValid && errors.length === 0,
    distribution,
    expected,
    errors,
  };
}
